"""Unit tests for interaction Pydantic models - edge cases and boundary values."""

from datetime import datetime

import pytest
from pydantic import ValidationError

from app.models.interaction import InteractionLog, InteractionLogCreate, InteractionModel


class TestInteractionLogCreate:
    """Tests for InteractionLogCreate request schema validation - edge cases."""

    def test_create_with_empty_string_kind_is_allowed(self) -> None:
        """Empty string for 'kind' field is allowed (no min_length constraint)."""
        model = InteractionLogCreate(learner_id=1, item_id=1, kind="")
        assert model.kind == ""

    def test_create_with_negative_learner_id(self) -> None:
        """Negative learner_id is technically allowed by int type (boundary value)."""
        model = InteractionLogCreate(learner_id=-1, item_id=1, kind="view")
        assert model.learner_id == -1

    def test_create_with_zero_item_id(self) -> None:
        """Zero item_id is technically allowed by int type (boundary value)."""
        model = InteractionLogCreate(learner_id=1, item_id=0, kind="view")
        assert model.item_id == 0


class TestInteractionModel:
    """Tests for InteractionModel response schema validation - edge cases."""

    def test_model_with_none_created_at_raises_validation_error(self) -> None:
        """InteractionModel requires created_at (not optional)."""
        with pytest.raises(ValidationError) as exc_info:
            InteractionModel(
                id=1,
                learner_id=1,
                item_id=1,
                kind="view",
                created_at=None,
            )
        assert "created_at" in str(exc_info.value)

    def test_model_with_large_id_values(self) -> None:
        """InteractionModel handles large integer ID values (boundary: max 32-bit signed int)."""
        large_id = 2**31 - 1
        model = InteractionModel(
            id=large_id,
            learner_id=large_id,
            item_id=large_id,
            kind="view",
            created_at=datetime.now(),
        )
        assert model.id == large_id
        assert model.learner_id == large_id
        assert model.item_id == large_id


class TestInteractionLog:
    """Tests for InteractionLog database model - edge cases."""

    def test_log_with_none_created_at_is_allowed(self) -> None:
        """InteractionLog allows created_at to be None (database default)."""
        log = InteractionLog(
            id=1,
            learner_id=1,
            item_id=1,
            kind="view",
            created_at=None,
        )
        assert log.created_at is None

    def test_log_with_none_id_is_allowed(self) -> None:
        """InteractionLog allows id to be None (auto-generated by database)."""
        log = InteractionLog(
            id=None,
            learner_id=1,
            item_id=1,
            kind="view",
            created_at=datetime.now(),
        )
        assert log.id is None